apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-pod
spec:
  containers:
    - name: gpu-test-container
      image: jupyter/base-notebook:latest
      resources:
        limits:
          nvidia.com/gpu: 1  # Request 1 GPU
      command: ["nvidia-smi"]
  restartPolicy: OnFailure

